In [2]:
## data explore

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

data = pd.read_csv('../data/final_dataset.csv')
data.info(), data.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ORISPL    1800 non-null   int64
 1   YEAR      1800 non-null   int64
 2   PSTATABB  1800 non-null   object
 3   NAMEPCAP  1800 non-null   float64
 4   CAPFAC    1800 non-null   float64
 5   SECTOR    1799 non-null   object
 6   PLFUELCT  1800 non-null   object
 7   PLNGENAN  1800 non-null   float64
 8   PLHTIAN   1800 non-null   float64
 9   PLCO2AN   1800 non-null   float64
 10  PLCO2RTA  1800 non-null   float64
 11  TREATED   1800 non-null   int64
 12  POST      1800 non-null   int64
dtypes: float64(6), int64(4), object(3)
memory usage: 182.9+ KB

(None, (1800, 13))

In [3]:
data.describe()

,ORISPL,YEAR,NAMEPCAP,CAPFAC,PLNGENAN,PLHTIAN,PLCO2AN,PLCO2RTA,TREATED,POST
count,1800.000000,1800.000000,1800.000000,1800.000000,1.800000e+03,1.800000e+03,1.800000e+03,1800.000000,1800.000000,1800.000000
mean,26228.133889,2020.408333,713.840444,0.259982,2.029037e+06,1.870077e+07,1.615095e+06,2229.022724,0.114444,0.474444
std,25641.546196,1.712991,714.537398,0.253487,2.964898e+06,2.797675e+07,2.743800e+06,13960.247591,0.318439,0.499485
min,54.000000,2018.000000,25.000000,0.000000,-5.759600e+04,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
25%,2854.000000,2019.000000,122.850000,0.027100,5.775175e+04,6.187745e+05,3.523400e+04,898.739250,0.000000,0.000000
50%,7845.000000,2020.000000,511.350000,0.170450,4.869580e+05,4.575512e+06,2.986355e+05,1400.801500,0.000000,0.000000
75%,55247.000000,2022.000000,1086.200000,0.462400,3.379811e+06,2.903903e+07,1.976197e+06,2140.404500,0.000000,1.000000
max,64854.000000,2023.000000,3718.200000,0.939800,1.763180e+07,1.739933e+08,1.793342e+07,533536.520000,1.000000,1.000000

In [8]:
data.nunique()

ORISPL       350
YEAR           6
PSTATABB       9
NAMEPCAP     404
CAPFAC      1415
SECTOR         6
PLFUELCT       3
PLNGENAN    1757
PLHTIAN     1758
PLCO2AN     1722
PLCO2RTA    1723
TREATED        2
POST           2
dtype: int64

In [10]:
data[data['SECTOR'].isna()]

,ORISPL,YEAR,PSTATABB,NAMEPCAP,CAPFAC,SECTOR,PLFUELCT,PLNGENAN,PLHTIAN,PLCO2AN,PLCO2RTA,TREATED,POST
435,7258,2018,MI,161.7,0.0358,NaN,GAS,50703.0,594638.0,35339.0,1393.953,0,0

In [11]:
data.head()

,ORISPL,YEAR,PSTATABB,NAMEPCAP,CAPFAC,SECTOR,PLFUELCT,PLNGENAN,PLHTIAN,PLCO2AN,PLCO2RTA,TREATED,POST
0,7818,2020,IL,173.0,0.0196,Electric Utility,GAS,29764.0,248594.0,14645.0,984.042,0,0
1,10865,2020,IL,335.0,0.4016,Industrial CHP,COAL,1178599.0,4822371.0,486846.0,826.144,0,0
2,10866,2020,IL,64.0,0.1276,Industrial CHP,GAS,71548.0,394715.0,23069.0,644.851,0,0
3,55279,2020,IL,1086.2,0.0808,IPP Non-CHP,GAS,768846.0,7770819.0,461804.0,1201.292,0,0
4,889,2020,IL,1894.1,0.2447,IPP Non-CHP,COAL,4060737.0,42583478.0,4466152.0,2199.675,0,0